// <auto-generated />
using System;
using Huellitas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Huellitas.Data.Migrations
{
    [DbContext(typeof(HuellitasContext))]
    [Migration("20260308162451_MigracionCompleta")]
    partial class MigracionCompleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Huellitas.Core.Entities.Categoria", b =>
                {
                    b.Property<int>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCategoria"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("idCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Detalle", b =>
                {
                    b.Property<int>("idDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDetalle"));

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("idPedido")
                        .HasColumnType("integer");

                    b.Property<int>("idProducto")
                        .HasColumnType("integer");

                    b.Property<decimal>("precioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idDetalle");

                    b.HasIndex("idPedido");

                    b.HasIndex("idProducto");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Devolucion", b =>
                {
                    b.Property<int>("idDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDevolucion"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("fechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idPedido")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.Property<decimal>("montoReembolso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("idDevolucion");

                    b.HasIndex("idPedido")
                        .IsUnique();

                    b.HasIndex("idUsuario");

                    b.ToTable("Devolucion");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Favorito", b =>
                {
                    b.Property<int>("idFavorito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idFavorito"));

                    b.Property<DateTime>("fechaAgregado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idProducto")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.HasKey("idFavorito");

                    b.HasIndex("idProducto");

                    b.HasIndex("idUsuario");

                    b.ToTable("Favorito");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Notificacion", b =>
                {
                    b.Property<int>("idNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idNotificacion"));

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.Property<bool>("leida")
                        .HasColumnType("boolean");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("idNotificacion");

                    b.HasIndex("idUsuario");

                    b.ToTable("Notificacion");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Pedido", b =>
                {
                    b.Property<int>("idPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPedido"));

                    b.Property<string>("direccionEnvio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("metodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idPedido");

                    b.HasIndex("idUsuario");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.PedidoEstado", b =>
                {
                    b.Property<int>("idPedidoEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPedidoEstado"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idPedido")
                        .HasColumnType("integer");

                    b.Property<string>("observacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("idPedidoEstado");

                    b.HasIndex("idPedido");

                    b.ToTable("PedidoEstado");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Producto", b =>
                {
                    b.Property<int>("idProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idProducto"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("idCategoria")
                        .HasColumnType("integer");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("pesoKg")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stockActual")
                        .HasColumnType("integer");

                    b.Property<int>("stockMinimo")
                        .HasColumnType("integer");

                    b.HasKey("idProducto");

                    b.HasIndex("idCategoria");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Resenia", b =>
                {
                    b.Property<int>("idResenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idResenia"));

                    b.Property<int>("calificacion")
                        .HasColumnType("integer");

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idProducto")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.HasKey("idResenia");

                    b.HasIndex("idProducto");

                    b.HasIndex("idUsuario");

                    b.ToTable("Resenia");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Rol", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idRol"));

                    b.Property<string>("tipoRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("idRol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("idRol")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("segmentoCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("idUsuario");

                    b.HasIndex("idRol");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Detalle", b =>
                {
                    b.HasOne("Huellitas.Core.Entities.Pedido", "Pedido")
                        .WithMany("detalles")
                        .HasForeignKey("idPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Huellitas.Core.Entities.Producto", "producto")
                        .WithMany()
                        .HasForeignKey("idProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("producto");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Devolucion", b =>
                {
                    b.HasOne("Huellitas.Core.Entities.Pedido", "Pedido")
                        .WithOne("devolucion")
                        .HasForeignKey("Huellitas.Core.Entities.Devolucion", "idPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Huellitas.Core.Entities.Usuario", "Usuario")
                        .WithMany("devoluciones")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Favorito", b =>
                {
                    b.HasOne("Huellitas.Core.Entities.Producto", "Producto")
                        .WithMany("favoritos")
                        .HasForeignKey("idProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Huellitas.Core.Entities.Usuario", "Usuario")
                        .WithMany("favoritos")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Notificacion", b =>
                {
                    b.HasOne("Huellitas.Core.Entities.Usuario", "Usuario")
                        .WithMany("notificaciones")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Pedido", b =>
                {
                    b.HasOne("Huellitas.Core.Entities.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.PedidoEstado", b =>
                {
                    b.HasOne("Huellitas.Core.Entities.Pedido", "Pedido")
                        .WithMany("estados")
                        .HasForeignKey("idPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Producto", b =>
                {
                    b.HasOne("Huellitas.Core.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Resenia", b =>
                {
                    b.HasOne("Huellitas.Core.Entities.Producto", "Producto")
                        .WithMany("resenias")
                        .HasForeignKey("idProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Huellitas.Core.Entities.Usuario", "Usuario")
                        .WithMany("resenias")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Usuario", b =>
                {
                    b.HasOne("Huellitas.Core.Entities.Rol", "rol")
                        .WithMany("usuarios")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("rol");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Pedido", b =>
                {
                    b.Navigation("detalles");

                    b.Navigation("devolucion");

                    b.Navigation("estados");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Producto", b =>
                {
                    b.Navigation("favoritos");

                    b.Navigation("resenias");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Rol", b =>
                {
                    b.Navigation("usuarios");
                });

            modelBuilder.Entity("Huellitas.Core.Entities.Usuario", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("devoluciones");

                    b.Navigation("favoritos");

                    b.Navigation("notificaciones");

                    b.Navigation("resenias");
                });
#pragma warning restore 612, 618
        }
    }
}
